// <auto-generated />
using Ecommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231212192420_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ecommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Experience the very beginning as we go back to the first generation that started it all.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Pok%C3%A9mon_Red_and_Blue_cover_art.webp/546px-Pok%C3%A9mon_Red_and_Blue_cover_art.webp.png",
                            Price = 80.00m,
                            Title = "Pokemon Red, Blue and Yellow bundle"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Experience the sequels that changed everything and perfected the formula for the biggest franchice in the early 2000s.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/4c/Pok%C3%A9mon_box_art_-_Gold_Version.png",
                            Price = 299.99m,
                            Title = "Pokemon Gold and Silver bundle"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The wild child of the ever growing family of triple pack games and the start of the advanced generation of poekmon games, with more features than you could possibly count!",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/be/PokemonRubySapphireBox.jpg",
                            Price = 479.95m,
                            Title = "Pokemon Ruby and Sapphire bundle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
